/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/
        
/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.odata;

import java.util.List;

import junit.framework.TestCase;

import org.mule.modules.aplicor.model.sync.SyncContact;
import org.odata4j.core.Guid;

public class ODataModuleTest extends TestCase {
	
	private ODataModule module;
	@Override
	protected void setUp() throws Exception {
		module = new ODataModule();
		module.setBaseServiceUri("https://muleqa.aplicor.net/a7/OData.svc/");
		module.setUsername("4264DAA0-A5C7-4BB9-AE40-6B4AFABE64F4:Mulesoft");
		module.setPassword("Mulesoft11");
		module.setNamingFormat(PropertyNamingFormat.UPPER_CAMEL_CASE);
		module.init();
	}
	
	public void _testReadEntity() {
		List<Object> contacts = module.getEntitiesAsPojos("org.mule.modules.aplicor.model.sync.SyncContact", "SyncContactSet", null, null, null, null, null);
		
		for (Object obj : contacts) {
			System.out.println(obj);
		}
	}
	
	public void testCreateContact() {
		SyncContact contact = new SyncContact();
		contact.setBusinessPhone("111");
		contact.setCompany("Mulesoft");
		contact.setEmailAddress("mariano.gonzalez2@mulesoft.com");
		contact.setExternalId(Guid.fromString("3331"));
		contact.setFirstName("Mariano");
		contact.setLastName("Gonzalez");
		contact.setGoogleId("googleId");
		contact.setHomePhone("333-444");
//		contact.setLastEditedDate(new Date());
		contact.setPersonalPhone("444");
		contact.setMiddleName("Luis");
		contact.setSalutation("Ing.");
		contact.setTitle("Software Engineer");
		
		this.module.createEntityFromPojo(contact, null);
	}
	
	
}
